#zadanie aso Pozdrawiamy panie Arku:) Arkadiusz Kacper 2tei
#versionn: public test 0.3
#news: Improved optimisation


network:
  ethernets:
    enp0s3:
      dhcp4: True/False
      addresses: [IP_ADDRESS/NETMASK]
      routes:
        - to: default
          via: {default gateway}
      nameservers:
       addresses: [NAMESERVER_1, NAMESERVER_2]
    version: 2
